### ISSUE TITLE
what happens if I later use command line msbuild.exe?

### ISSUE THREAD

**Issue by necroscope** [golavr/ConfigurationTransformSample#1]
Hello,

We built the transforms in vs 2017 but when I use msbuild.exe against the solution file and feed it an environment such as msbuild /p:Configuration=release  will it do the transform even though the command line build is not using visual studio?  We want to get this to work in jenkins and cruisecontrol where we use the command line msbuild and still want the transforms to take place.  Thanks for your help!

**Comment by golavr** [comment]
I never tried to run it outside VS.
I do know it will run on machines w/o the extension installed, but i assume it will require some dependencies.

**Comment by blade2005** [comment]
@necroscope did you ever find an answer to this issue?
